### ISSUE TITLE
Problem with the freq of digitizer in raw files

### ISSUE THREAD

**Issue by georgievgeorgi** [PADME-Experiment/padme-fw#13]
File daq_b01_2016_07_03_13_43_13 contains data by V1742 operating at 5GHz.
Data format version 2 says that filed "Frq" in trigger event should be 0b00 for 5GHz but we found it 0b10.
Simple command shows the problem
hexdump -s 36 -n 4 -e '"%08_ax " 1/4 "%08X\n"' daq_b01_2016_07_03_13_43_13
The problem seems to be here:
https://github.com/PADME-Experiment/padme-fw/blob/master/PadmeDAQ/src/PEvent.c#L61

**Comment by eleonardi** [comment]
Fixed in develop
